[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1634FF"
backgroundColor = "#F3F7FC"
secondaryBackgroundColor = "#E8EDFF"
textColor = "#000033"
font = "sans serif"
